#+title: 从零开始GB2312

[[http://openstd.samr.gov.cn/bzgk/gb/index][国家标准全文公开系统]]

标准号：[[http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=5664A728BD9D523DE3B99BC37AC7A2CC][GB/T 2312-1980]]
中文标准名称：信息交换用汉字编码字符集 基本集
英文标准名称：Code of Chinese graphic character setfor information interchange--Primary set
发布日期 1980-03-09
实施1981-05-01
 根据2017年第7号公告和强制性标准整合精简结论，自2017年3月23日起,该标准转化为推荐性标准，不再强制执行。

GB/T 2312-1980: 682 signs and 6763 Chinese Characters, 7445 in total



[[https://zh.wikipedia.org/wiki/%E6%B1%89%E5%AD%97%E7%BC%96%E7%A0%81%E5%AD%97%E7%AC%A6%E9%9B%86][汉字编码字符集]]

图书：[[http://book.ucdrs.superlib.net/views/specific/2929/bookDetail.jsp?dxNumber=000005952514&d=EC6ECEB4D92148819D21099D7A25076F][中文信息处理技术教程]], 【ISBN号】7-302-11761-6


[[https://web.archive.org/web/20001216022100/http://tronweb.super-nova.co.jp/characcodehist.html][A Brief History of Character Codes in North America, Europe, and East Asia]]

[[http://tools.jb51.net/table/gb2312][GB2312简体中文编码表]]

-----

GB2312：一个小于127的字符意义与原来的相同，但是两个大于127的字符连在一
起时，就表示一个汉字；前面的一个字节（高字节）从0xA1用到0xF7，后面一个
字节（低字节）从0xA1到0xFE；其中，在ASCII里本来就有个的数字、标点、字
母都统统重新编了两个字节长的编码，这就是常说的“全角”字符，而原来在127
号以下的那些就叫“半角”字符

GBK：不再要求低字节一定是127号之后的编码，只要第一个字节是大于127就固
定表示这是一个汉字的开始，不管后面跟的是不是扩展字符集里的内容

-----

[[http://openstd.samr.gov.cn/bzgk/gb/index][Zpix (最像素)]] is a pixel font supporting English, Traditional Chinese,
Simplified Chinese and Japanese.

-----

GB2312为7位双字节编码（共128*128），为了避开ASCII编码中的控制字符
（0~31和127）以及空格符（32），最后只剩下94位可用，遵循ISO 2022标准的
编码方案都是如此。具体细节你可以看一下EUC和ISO/IEC 2022。你说的
0x9A~0xFF这些空间是国标码变形后得来的。设计时采用的是区位码，有了区位
码才会在编码空间上作映射。

作者：erli
链接：https://www.zhihu.com/question/21923181/answer/228169822
来源：知乎


其实你要是去翻 JIS-X-0208、GB-2312 和 KS-X-1001 这三个码表你可以发现这
几个表的结构几乎一模一样，因为他们都是遵循 ECMA-35 的 94×94 规格，而且
有相互参考

-----

机内码

区位码

字形码

-----

[[https://zh.wikipedia.org/wiki/ISO/IEC_2022][ISO/IEC 2022]]
[[https://zhuanlan.zhihu.com/p/27120673][刨根究底字符编码之六——简体汉字编码中区位码、国标码、机内码、外码、字形码的区别及关系]]

-----

* 术语

- 位组 :: 一个字符的二进制位的有序集合。
- 代码；编码字符集 :: 用一组明确的规则确立字符集；并确立该字符集中的字
  符与其 *位组* 之间一一对应关系。
- 字节 :: 作为一个单位来处理的二进制位串。
- 图形字符 :: 它是一种不同于控制字符的字符，通常这种字符具有可视图形，
  它可以用手写、印刷或显示等方式直观地表示出来。
- 转义序列 :: 用于扩充代码的 *位组* 串。它由两个或两个以上的位组构成，
  其中第一个位组是转移字符（ESC）。
- 指明 :: 在预先制订的一些字符集中，用规定的方法指出其某一特定的字符集。
- 调用 :: 使指明的编码字符集成为能使用的状态。
- 表示 ::
  1. 按在指明和调用的字符集中字符的意义，使用规定的位组。
  2. 按增补的控制功能意义使用转义序列。

* 图形字符

GB/T 2312-1980收录一般符号、数字、拉丁字母、日文假名、汉语拼音、汉字等，
共7445个图形字符，其中汉字6763个，分成两级：第一级3755个，第二级3008个。

* 编码

任意一个图形字符都采用两个字节表示，









GB2312 是汉字字符集和编码的代号，中文全称为“信息交换用汉字编码字符集”，
由中华人民共和国国家标准总局发布，一九八一年五月一日实施。GB 是“国标”
二字的汉语拼音缩写。

GB2312 字符集 (character set) 只收录简化字汉字，以及一般常用字母和符号，
主要通行于中国大陆地区和新加坡等地。GB2312 共收录有 7445 个字符，其中
简化汉字 6763 个，字母和符号 682 个。

GB2312 将所收录的字符分为 94 个区，编号为 01 区至 94 区；每个区收录 94
个字符，编号为 01 位至 94 位。GB2312 的每一个字符都由与其唯一对应的区
号和位号所确定。例如：汉字“啊”，编号为 16 区 01 位。


GB2312 字符集的区位分布表





区号	字数	字符类别
1	94	一般符号
2	72	顺序号码
3	94	拉丁字母
4	83	日文假名
5	86	Katakana
6	48	希腊字母
7	66	俄文字母
8	63	汉语拼音符号
9	76	图形符号
10-15
备用区
16-55	3755	一级汉字，以拼音为序
56-87	3008	二级汉字，以笔划为序
88-94
备用区



GB2312 原始编码 (encoding) 是对所收录的每个字符都用两个字节 (byte) 表
示。第一字节为“高字节”，由字符的区号值加上 32 而形成；第二字节为“低字
节”，由字符的位号值加上 32 而形成。例如：汉字“啊”，编号为 16 区 01 位。
它的高字节为 16 + 32 = 48 (0x30)，低字节为 01 + 32 = 33 (0x21)，合并而
成的编码为 0x3021。

在区位号值上加 32 的原因大慨是为了避开低值字节区间。

由于 GB2312 原始编码与 ASCII 编码的字节有重叠，现在通行的 GB2312 编码
是在原始编码的两个字节上各加 128 修改而形成。例如：汉字“啊”，编号为 16
区 01 位。它的原始编码为 0x3021，通行编码为 0xB0A1。

如果不另加说明，GB2312 常指这种修改过的编码。

GB2312的编码范围是0xA1A1-0x7E7E，去掉未定义的区域之后可以理解为实际编
码范围是0xA1A1-0xF7FE。

上面这句有误，应该说GB2312的每一个汉字由两个字节构成，其中每一个字节的
范围都在0xA1 ~0xFE，正好每一个字节都有94个编码范围，与区位码个数完全对
应。

EUC-CN可以理解为GB2312的别名，和GB2312完全相同。

区位码更应该认为是字符集的定义，定义了所收录的字符和字符位置，而GB2312
及EUC-CN是实际计算机环境中支持这种字符集的编码。HZ和 ISO-2022-CN是对应
区位码字符集的另外两种编码，都是用7位编码空间来支持汉字。区位码和
GB2312编码的关系有点像 Unicode和UTF-8。


我 46 50
看 31 20
你 36 67
是 42 39
个 24 86
大 20 83
笨 17 31
蛋 21 16




d5e2 c0ef cac7 d6d0 cec4 a3ac b6ba bac5
这   里    是   中   文   ，    逗   号

a3ac bee4 bac5 a1a3 0a   d3d0 c8ab bdc7 a3c1
，   句   号    。   '\n' 有    全   角   Ａ
                    linefeed
a3c2 a1a1 a3c3 a3c4 a3ba b5c8 a3a8 a3e6 a3f5 a3a9 a3e8 a3e1 a3ef a1a3 0a
Ｂ   '　'  Ｃ   Ｄ   ：    等   （   ｆ   ｕ    ）   ｈ   ａ   ｏ    。   '\n'
    全角空格
bbb9 d3d0 6261 6e20 6a69 616f 206c 696b 6520 6120 4162 4220 3e5f 3c2e 0a
还   有    b a  n ' 'j i  a o  ' 'l i k  e' ' a' ' A b  B' ' > _  < . '\n'
                 半角空格
