#+title: anythingarian n.

* Meaning

[[https://www.etymonline.com/word/anythingarian][Etymonline]]: "one indifferent to religious creeds, one 'that always
make their interest the standard of their religion,'" 1704, originally
dismissive, from anything on model of /trinitarian/, /unitarian/, etc.

[[https://www.oed.com/view/Entry/8980][OED]]: A person who does not subscribe to any fixed or established set
of beliefs.

[[https://www.collinsdictionary.com/us/dictionary/english/anythingarian][Collins]]: [derogatory, informal] a person who adheres to no particular
creed.

[[https://www.merriam-webster.com/dictionary/anythingarian][Webster]]: one that holds no particular creed or dogma

- Such Bifarious Anythingarians, that always make their Interest the
  Standard of their Religion.
- If man makes his beliefs, why should I not make my own?  I will be
  an Anythingarian, and leave dreams to Emanuel Swedenborg!
- [[https://www.marxists.org/archive/lenin/works/1914/may/04.htm][The Ideological Struggle in the Working-Class Movement]] A worker who
  takes an anythingarian attitude towards the history of his own
  movement cannot be considered class-conscious.

#+begin_quote
When a man, in all companies, abounds in religious small talk, but
carefully avoids saying any thing that has much point, or is very
decided any way, I set him down as an Anythingarian.

When a man professes to think well of two opposite schemes of
religion, and declares that he likes them both, and sees no important
difference between them; or when two books, written on opposite sides
of the same question, are presented to him, and after examination he
declares that he admires them both, and thinks they are equally good:
I set him down as an Anythingarian.

When a man acknowledges the truth as the instrument of the conversion
and sanctification of men, and at the same time embraces in his
fellowship those who understandingly hate and oppose the truth, I set
him down as an Anythingarian.

When two men of opposite principles go and converse with a third
person for the purpose of ascertaining what his principles are, and
each comes away with the impression that he agrees with him, I set
down that third person as an Anythingarian.

When a man professes to believe the doctrines of the bible to be true,
and acknowledges that they are plainly and abundantly taught in the
scriptures, and at the same time considers the preaching of them as
unprofitable and useless, if not positively injurious, and so
converses with the opposers of those doctrines that they consider him
as much opposed as they are, I set down that man as an Anythingarian.

When a man professes to believe the doctrines of the bible to be true,
and declares that he is willing to have them preached, but is always
in a tremor when he hears any of them mentioned from the pulpit, for
fear they should be carried too far, I set him down as an
Anythingarian.

When a man professes to believe the doctrines of the bible to be true,
and declares that he understands them, and is edified with them, but
is afraid of having them preached, lest other people should not
understand them and be edified, I set him down as an Anythingarian.

When a man flatters me to my face, and speaks highly of me to my
particular friends, but talks against me to my enemies, and elsewhere
throws out sly hints to my disadvantage, I set him down as an
Anythingarian.

When a man tells me that he agrees with me in my opinions, and admires
my method of stating and vindicating them, and wish es he was only
able to do it as well, and at the same time is very intimate with
those who oppose my principles, and encourages all their efforts to
bring those principles into disrepute, I set down that man as an
Anythingarian.

When a church has a confession of faith, and require all whom they
receive as members to give their public assent to it, and at the same
time do not carefully examine applicants to know whether they
understand and believe the doctrines contained in that confession, or
knowingly receive such as do not believe those doc trines, or retain,
without any effort at discipline, those members who openly oppose the
doctrines to which they have solemnly assented, I set down that church
as a body of Anythingarians.

When a church has a covenant, by which all the members have solemnly
bound themselves to walk with that church in all the ordinances of
the gospel, and yet suffer their members to walk away, whenever and
wherever they please, I think that church must be deeply tinctured
with Anythingarianism.

---[[https://books.google.com/books?id=a9MoAAAAYAAJ][The Religious Monitor, and Evangelical Repository]]
#+end_quote
