#+title: 写在 NOIP2017 之后
#+date: 2017-11-19 07:37:35

这是我的第一篇正式博文，算是尝试一下 Markdown 的语法，熟悉一下博客的使用，也借此回顾一下将近一年的OI生涯。

* 过去
:PROPERTIES:
:CUSTOM_ID: 过去
:END:
我一直对计算机这块比较感兴趣吧，感觉很好玩。曾经也尝试过学 Python ，然而还是弃了。就随便学了学 HTML 和 LaTex 。

上高中以前，压根不知道有 OI 这种东西，现在想想，如果早点知道该多好啊。

* 初识
:PROPERTIES:
:CUSTOM_ID: 初识
:END:
应该是高一上校本课选课的时候吧， cwx 和我才第一次知道 OI ，也花了不少时间去熟悉这门竞赛，也第一次知道程序不是简简单单写写就出来的，而是要“数据结构+算法”，语言只是最基础的东西。然后，凭着一番热情，我们慢慢开始走向一个 OIer 的道路。

** 语言
:PROPERTIES:
:CUSTOM_ID: 语言
:END:
语言当然是最基础的。

为了学 C ，我在学校图书馆里借了一本《21天学会 C 语言》， cwx 借了一本 C++ 的，然而没多久我们就都弃了，因为书写的实在有点无聊......

后来我发现了一本很好的书，是清华大学出版的《程序设计语言---​---C》， cwx 也找到了本类似的。不知道为什么，我感觉这本书很有趣，基本上每天早上都四点半起来看它，于是就慢慢学到了很基础的部分。

之后在寒假里发现了 MOOC 这个好东西，就报了一门《程序设计与算法（一）C语言程序设计》，它的《（二）算法基础》我也报了，不过因为当时感觉太难，没多久还是弃了。不过通过这两门课程，我知道了 OJ ，最先熟悉的就是 OpenJudge 了。

就这么学会了语言，接下来也就是学习算法的时候了。

** 算法
:PROPERTIES:
:CUSTOM_ID: 算法
:END:
仿佛在报《（二）》的时候我们的算法学习之路就正式开始了。这段时间磕磕绊绊，印象最深刻的就是“八皇后”和“熄灯问题”了。不过这门课我到底还是弃了，到底没学也没练。

在网上找书，第一次知道 刘汝佳 大神，也买了一本他的黑书。不过因为黑书前面介绍概念太多了，我看到NPC的时候就放弃了......（我怎么弃了这么多东西 -_-）不过还是找到了汝佳大神的白书和粉书，坚持看了一个学期的白书（然而看的很少）。

高一下学期这段时间，我开始发现很多不同的 OJ ，当时主要是在 VirtualJudge 和 洛谷 上做题。

算法当然是 OI 的核心，是不可能学完的，不过暂且就说到这里吧。

*** 分别 :(
:PROPERTIES:
:CUSTOM_ID: 分别
:END:
高一到底还是要分班的。最后 cwx 去了一班，我还留在二班，曾经要好不要好的同学也都到了不同的班级。我的 OI 之路也就是这个时候开始慢慢改变的吧。

* 刷题 :D
:PROPERTIES:
:CUSTOM_ID: 刷题-d
:END:
暑假还是很美好的，可以一整天坐在电脑面前，也不怎么要担心作业。

纠结了好久到底要看粉书还是白书，最终还是选择了粉书。

七月份我基本上用大半个下午的时间看粉书，也学到了不少算法，有过几个 "aha moment"，不过到底没怎么刷题（摊手）。

到了八月，就很欢乐了。先是5天的洛谷夏令营，被金牌大佬讲得体无完肤，基本上什么都听不懂，只能听听晚上的助学课，现在这个坑我还没开始填呢。

之后，在 Vijos 上，我照着训练计划把复赛题从 2003 年刷到 2013 年，感觉码力和思维可以说是有了质的飞跃吧，感觉萌萌哒 XD

cwx 八月份是在杭州上物竞，估计没弄太多 OI 。

然后很欢乐的， cwx 请我看了场电影，又吃了顿饭，还陪我剃了个头（我剃 XD），花了他两百多吧（仿佛从没吃过这么贵的烤肉）。期间惊奇地发现 xhy 成了二班班主任，符老大成了一班班主任，也是很无奈啊。 这顿饭到现在我都没有请回来，可能要到寒假了吧。

于是暑假就这么结束了，在开学前学校里，我补了暑假作业，还看了粉书上的图论，白书上也看了一部分，不过并没有看懂。

* 开学 :|
:PROPERTIES:
:CUSTOM_ID: 开学
:END:
开学的时候我是充满展望的吧，毕竟马上就是 NOIP2017 了。

九月中旬的时候，也不知怎么有的勇气，我找到 twj ，希望能有个地方弄竞赛，他竟然答应了。于是我就可以每周三天在晚二到文德楼弄竞赛了。然而 cwx 物竞没过，打算走读弄个 OI ，最终还是放弃了......

期间遇到了物竞没拿到省一但文化课第一的陆大佬，仿佛受到了激励，对 OI 更加展望了呢。

* 初赛
:PROPERTIES:
:CUSTOM_ID: 初赛
:END:
国庆前就开始慢慢准备初赛了，国庆后的一个星期，便是初赛。准备了不少，也就不说了吧。

那天发现我们学校还有一个高三的学长也在弄 OI ，然后就是感慨我们学校 OI 真的是弱啊。 到了天一，逛了逛校园，发现天一的生态园很欢乐。走到里面，有一个很三国的场景---​---一片竹林中一条小道，通向中央的一个大鼎，走进去沙沙地响（如果是陆大佬写应该会更有带入感吧 :p）。

果然考前都是颓，默了一遍 Dij 就开始考试了。然后，......

#+begin_verse
这是什么？怎么页脚写着“NOIP2016”？
这第一题是什么鬼？我一个选 C++ 的管你 Pascal 什么时候禁止？
主定理怎么被改了？
怎么怎么多数竞题？莫非我学的是假 OI ？
网络流？要完要完。 这第一道模拟题怎么这么眼熟？（事后才是到是15年的“幻方”，然而错了，要完要完）
这第四道的性质怎么看不出来啊？要完要完。
大整数？我前几天刚说不太可能会考 XD
#+end_verse

考试结束感觉要完......

无论如何，最终还是考了 80 分，比竞争线多了一道选择题 :D，然而 cwx 并没有过...... :(

cwx 暂时滚回高考，而我慢慢弄复赛。

这时候，我才真正发现我的 OI 之路会是一个人走过的吧。

* 复赛
:PROPERTIES:
:CUSTOM_ID: 复赛
:END:
其实关于复赛的，我都在日记里写了，这里就不细细说了。

复赛的时候遇到了市中的 xxy ，是个高三的大佬。

南航餐厅的饭菜还是很好吃的，比我们学校不知道要好多少。​+也亏我们学校天天在那儿宣传......+

复赛结束后的几天，我拿到了源码，去洛谷上自测了一下，能有320，不过感觉这次的省一线至少330...... 复赛后的期中考我算是彻底爆炸了，语文依旧是倒一，英语却没有正一，数学......算了别和我提数学...... -_- cwx 现在到好像门门功课搞得风声水起，佩服佩服。

无论如果，感觉复赛要完，真正的成绩就等明天了吧。​+也许我可以达成成就“复赛、期中考双爆炸”+

* 展望
:PROPERTIES:
:CUSTOM_ID: 展望
:END:
其实接下来基本上由不得我了，可能要暂时滚回（小）高考了，基本上就是看复赛的成绩吧。

当然，​*无论如何* OI 这条路我是不会放弃的。我 *flag* 立这儿了，我就不信这个邪。 接下来，对付复赛，主要是去刷题吧，难度自然是“提高+/省选-”及以上的，而如果想要更高，还要学习很多算法。

总之， OI 这条路我走了快一年，而还有一年，我会​*继续走下去*​无论是不是一个人，无论有多么难走，也无论结果怎样。

我暂时还不清楚要怎么走，但是我一定会坚持下来。

** UPD: 2017-11-21 15:45
:PROPERTIES:
:CUSTOM_ID: upd-2017-11-21-1545
:END:
成绩终于出来了。

从昨天早上我就开始等，物理课一上完我就跑到电脑前面查成绩，结果它告诉我“成绩未上传”，等一会看，又变成“18:00 公布初评成绩”，我也是很无奈。

然后晚一下课我又去看，发现 CCF 果不其然又跳水了，变成“11-21 8:30 公布初评成绩”。听说去年也是这样，可能这是 CCF 的传统吧。

于是今天我去看成绩，一开始没查成功，后来终于查到了：

#+begin_example
math  complexity  park  treasure  phalanx  cheese  总成绩
50    100         10    35        30       100     325
#+end_example

感觉还不错吧，不过 D1T1 怎么只有 50 分， D2T2 怎么这么高......果然民间自评和 CCF 还是有点出入的。

现在江苏的总体成绩还没出来，不过看到广东和浙江的成绩，我也就基本不抱什么希望了。诶，仿佛最多也就国二了（江苏的竞赛政策让我很无奈啊）。

不过我觉得我有点理由再弄竞赛了。

这几天一直在思考人生，想要理性地看高中弄 OI 是否真正值得，现在好像已经有了答案了吧。
