#+title: be survived by

From a sentence in [[https://en.wikipedia.org/wiki/Edsger_W._Dijkstra#EWD_manuscripts][Wiki: Edsger W. Dijkstra]]:

#+begin_quote
He and his wife Maria (Ria) Debets /were survived by/ their three
children: Marcus, Femke, and the computer scientist Rutger
M. Dijkstra.
#+end_quote

* LDOCE5

to live longer than someone else, usually someone closely related to
you -- used especially in newspaper articlessurvive somebody by 10
years/six months etc

- Charles survived his wife by three months.
- He is survived by his wife Sue.
- Monroe is survived by his wife, Regina, and two sons, Stanley and
  John.
- Noell was survived by five sons, two daughters, and his wife
  Elizabeth who died two weeks after his own death.
- Floirat is survived by a daughter and a grandson, who has assumed
  some of his business activities.
- The Merveilleuses survived the Incroyables by a couple of years.

* Collins

If you survive someone, you continue to live after they have died.

- Most women will survive their spouses.
- She is survived by two daughters from her first marriage.
  她身后留下了头婚时生的两个女儿。

* AHD

To live longer than; outlive:

- She survived her husband by five years.


* Macmillan Dictionary

[[https://www.macmillandictionary.com/us/dictionary/american/be-survived-by-someone][be survived by someone]]: if you are survived by someone, they are still
alive after you have died

- Santos is survived by his wife /of/ 49 years. (神奇，不造为啥用 of)


* A article

Here's an [[https://www.joincake.com/blog/survived-by/][article]] explaining the phrase /be survived by/.

- Elizabeth is survived by her brother and wife Ben and Louise
  Jackson, sister and husband Jan and Shawn Metz; and her
  sister-in-law, Selena Zimmer. Her three sons and their wives Zach
  and Joy Jackson, Henry and Valerie Jackson, and Ned and Chloe
  Jackson; grandchildren, Mitzi Jackson, Lacey Jackson, Erik Jackson,
  and Oliver Jackson, as well as her many nephews and nieces.

- Surviving Boris are his parents, Nellie and Jerry Smith, as well as
  his sister, Geraldine. He is also survived by a loving wife of 16
  years, Emily, and their four children, Rose, Mandy, Sam, and Harry.

- She will be sorely missed and survived by her brother Max
  Young. Children: Leslie (Carter) Sanders and Kirk Carter, son-in-law
  Morgan Sanders and son from another mother, George Golding;
  grandchildren: Anna, Brendan, Cameron, and Denise;
  great-grandchildren: Lisa and Paula.
